name: Test
on: [ push, pull_request ]
jobs:
  sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SQLite, git
        run: |
          sudo apt-get install -y git sqlite3
        shell: bash
      - name: Checkout MalwareDB
        run: |
          git clone https://github.com/malwaredb/malwaredb-rs.git
      - name: Create database
        run: |
          sqlite3 test.db < malwaredb-rs/crates/server/src/db/malwaredb_sqlite.sql
      - name: Load sources
        run: |
          for src in `ls sources/*.sql`
          do
            sqlite3 test.db < $src
          done
          ls -la test.db
